# Generated by Django 5.0.2 on 2024-02-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('amount', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('amount', 'AMOUNT'), ('percent', 'PERCENT')], default='percent', max_length=7)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
