# Generated by Django 5.0.2 on 2024-03-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_description_en_category_description_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='title_uk',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
