# Generated by Django 4.2.2 on 2024-07-08 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_material_title_en_material_title_uk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('value_uk', models.CharField(blank=True, max_length=128, null=True)),
                ('value_en', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_views',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productvariantinfo',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='store.color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, to='store.material'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='store.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='store.size'),
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('name_uk', models.CharField(blank=True, max_length=128, null=True)),
                ('name_en', models.CharField(blank=True, max_length=128, null=True)),
                ('filter_fields', models.ManyToManyField(related_name='filter_fields', to='store.filterfield')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='filter',
            field=models.ManyToManyField(related_name='filter', to='store.filter'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='filter_field',
            field=models.ManyToManyField(related_name='filter', to='store.filterfield'),
        ),
    ]
