# Generated by Django 4.2.2 on 2024-07-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_filterfield_category_image_product_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_image', to='store.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantinfo',
            name='product_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variant_info', to='store.productvariant'),
        ),
    ]
