# Generated by Django 4.2.2 on 2024-07-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productvariantimage_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='store.productvariant'),
        ),
    ]
