# Generated by Django 4.2.2 on 2024-07-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_productvariant_filter_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='filter_field',
            field=models.ManyToManyField(related_name='filter_field', to='store.filterfield'),
        ),
    ]
