# Generated by Django 4.2.2 on 2024-07-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productvariant_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='filter_field',
            field=models.ManyToManyField(related_name='product_variants', to='store.filterfield'),
        ),
    ]
