# Generated by Django 4.2.2 on 2024-07-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productvariant_filter_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='colors', to='store.color'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, related_name='materials', to='store.material'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='sizes', to='store.size'),
        ),
    ]
