version: '3'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB={POSTGRES_DB}
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    image: tep-core:dev
    build: .
    command:
      bash -c "
      sleep 1
      && ./manage.py migrate
      && ./manage.py collectstatic --noinput
      && ./manage.py compilemessages
      && ./manage.py runserver 0.0.0.0:8000"
      # && gunicorn --bind 0.0.0.0:8000 tep.wsgi:application"
    volumes:
      - .:/app
      - ./static:/var/static
      - ./uploads:/var/uploads
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - redis
      - db
    links:
      - redis:redis
    env_file:
      - .env

  celery:
    image: tep-core:dev
    depends_on:
      - db
      - redis
    env_file:
       - .env
    volumes:
      - .:/app
    command: >
      bash -c "
              sleep 3 &&
              celery -A tep worker -E -B -ldebug
              "

  redis:
    image: redis
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/redis_data:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "${REDIS_PASSWORD}"

volumes:
  postgres_data:
