version: '3'

networks:
  db-network:
    driver: bridge

services:
  web:
    image: hordiirushynets/tep-core:latest
    build: .
    command:
      bash -c "
      sleep 1
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && gunicorn --bind 0.0.0.0:8000 backend.wsgi:application"
    volumes:
      - .:/app
      - ./static:/var/static
      - ./uploads:/var/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  celery:
    image: hordiirushynets/tep-core:latest
    depends_on:
      - db
    env_file:
       - .env
    volumes:
      - .:/app
    command: >
      bash -c "
              sleep 3 &&
              celery -A backend worker -E -B -ldebug
              "

  db:
    image: bitnami/pgpool:4
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-network

  pgbouncer-master:
    image: edoburu/pgbouncer:latest
    volumes:
      - ./docker/pgbouncer/pgbouncer_master.ini:/etc/pgbouncer/pgbouncer.ini
      - ./docker/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    ports:
      - 5432
    networks:
      - db-network

  pgbouncer-replica:
    image: edoburu/pgbouncer:latest
    volumes:
      - ./docker/pgbouncer/pgbouncer_slave.ini:/etc/pgbouncer/pgbouncer.ini
      - ./docker/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    ports:
      - 5432
    networks:
      - db-network

