# Generated by Django 4.2.2 on 2024-07-12 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tep_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEPUserSocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn')], default='instagram', max_length=50)),
                ('url', models.URLField(default='#')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
