# Generated by Django 4.2.2 on 2024-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productvariant_colors_and_more'),
        ('tep_user', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_variants',
            field=models.ManyToManyField(blank=True, related_name='product_variants', to='store.productvariant'),
        ),
    ]
