# Generated by Django 4.2.2 on 2024-07-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tep_user', '0003_alter_cart_product_variants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
