# Generated by Django 4.2.2 on 2024-08-03 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('post_type', models.CharField(max_length=100)),
                ('tep_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_number', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
