# Generated by Django 4.2.2 on 2024-07-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0003_dimensionalgrid_dimensionalgridsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='vacancy/images/')),
                ('title', models.TextField()),
                ('address', models.TextField()),
                ('employment_type', models.TextField()),
                ('description', models.TextField()),
                ('about_company', models.TextField()),
                ('duties', models.ManyToManyField(related_name='vacancy', to='store.filterfield')),
            ],
        ),
    ]
