# Generated by Django 4.2.2 on 2024-07-25 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=128)),
                ('city_uk', models.CharField(default=None, max_length=128, null=True)),
                ('city_en', models.CharField(default=None, max_length=128, null=True)),
                ('city_ru', models.CharField(default=None, max_length=128, null=True)),
                ('region', models.CharField(default=None, max_length=128)),
                ('region_uk', models.CharField(default=None, max_length=128, null=True)),
                ('region_en', models.CharField(default=None, max_length=128, null=True)),
                ('region_ru', models.CharField(default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_uk', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ru', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_uk', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ru', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_uk', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ru', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_uk', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_ru', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='vacancy/images/')),
                ('title', models.CharField(max_length=128)),
                ('title_uk', models.CharField(max_length=128, null=True)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('description', models.TextField()),
                ('description_uk', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('about_company', models.TextField()),
                ('about_company_uk', models.TextField(null=True)),
                ('about_company_en', models.TextField(null=True)),
                ('about_company_ru', models.TextField(null=True)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='vacancy.address')),
                ('scope_of_work', models.ManyToManyField(to='vacancy.scopeofwork')),
                ('tag', models.ManyToManyField(to='vacancy.tag')),
                ('type_of_employment', models.ManyToManyField(to='vacancy.typeofemployment')),
                ('type_of_work', models.ManyToManyField(to='vacancy.typeofwork')),
            ],
        ),
    ]
