# Generated by Django 4.2.2 on 2024-07-12 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='content_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='content_uk',
            new_name='description_uk',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 4, 12, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='additional_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='additional_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='additional_description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 4, 12, 0, 0), upload_to='blog_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='types',
            field=models.CharField(choices=[('complexity', 'Complexity'), ('requirements', 'Requirements'), ('what_materials', 'Materials'), ('for_children', 'For children')], default='complexity'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_uk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
