# Generated by Django 4.2.2 on 2024-07-18 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colour', to='store.color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='filter_field',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='store.filterfield'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material', to='store.material'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variants',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='store.productvariant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size', to='store.size'),
        ),
    ]
