# Generated by Django 4.2.2 on 2024-07-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tep_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tep_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
