name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: sudo docker-compose pull

    - name: Stop and remove old containers (if any)
      run: sudo docker-compose down --remove-orphans

    - name: Start containers
      run: sudo docker-compose up -d
