name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: sudo docker pull hordiirushynets/tep-core:latest

    - name: Delete old Docker container
      run: sudo docker rm -f tep-core-container || true

    - name: Run Docker container
      run: sudo docker run -d -p 8000:8000 --name tep-core-container hordiirushynets/tep-core:latest
