name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker-login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Docker build
      run: docker-build -t cicd-pipeline
    - name: Push to dockerhub
      run: docker push hordii-rushynets/cicd-pipeline:latest
