name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Compose Action
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "docker-compose.yaml"

    - name: Push Docker Image to Docker Hub
      run: docker push hordiirushynets/tep-core:latest

    - name: Run Django migrations
      run: docker-compose run web python manage.py migrate

    - name: Collect static files (if needed)
      run: docker-compose run web python manage.py collectstatic --noinput

    - name: Check Docker Compose logs
      run: docker-compose logs web
