name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: tep
          POSTGRES_USER: tep
          POSTGRES_PASSWORD: super_pass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Check if Docker image exists
      id: check_image
      run: |
        if ! docker pull tep-core:latest --quiet; then
          echo "Image tep-core:latest does not exist or access denied."
          exit 1
        fi

    - name: Set up Docker Compose Action
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "docker-compose.yaml"

    - name: Wait for Postgres and Redis to be ready
      run: |
        docker-compose run web sh -c "until pg_isready -h db -U tep; do sleep 1; done"
        docker-compose run web sh -c "until redis-cli -h redis ping; do sleep 1; done"

    - name: Push Docker Image to Docker Hub
      run: docker push hordiirushynets/tep-core:latest

    - name: Run Django migrations
      run: docker-compose run web python manage.py migrate

    - name: Collect static files (if needed)
      run: docker-compose run web python manage.py collectstatic --noinput

    - name: Check Docker Compose logs
      run: docker-compose logs web
